//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employment
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public System.DateTime EmploymentDate { get; set; }
        public Nullable<System.DateTime> DateOfDismissal { get; set; }
        public string Company { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
