//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Students()
        {
            this.Employment = new HashSet<Employment>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Nationality { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string IdentityDocument { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNumber { get; set; }
        public string IssuedBy { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public string PermanentRegistrationAddress { get; set; }
        public string IIAN { get; set; }
        public string ITN { get; set; }
        public double GPA { get; set; }
        public bool IsOrphan { get; set; }
        public bool IsInvalid { get; set; }
        public string CauseOfDisability { get; set; }
        public int SpecialityID { get; set; }
        public string FormOfStudy { get; set; }
        public string BasicEducation { get; set; }
        public string TypeOfFinancing { get; set; }
        public Nullable<int> GroupID { get; set; }
        public int StatusID { get; set; }
        public Nullable<bool> IsEmployed { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employment> Employment { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Specialities Specialities { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
